# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FFmpeg-Command
version:      0.13
version_from: lib/FFmpeg/Command.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Class::ErrorHandler:           0
    IPC::Run:                      0
    MIME::Types:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
