--- #YAML:1.0
name:               FFmpeg-Command
version:            0.18
abstract:           A wrapper class for ffmpeg command line utility.
author:
    - Gosuke Miyashita <gosukenator@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
    Class::ErrorHandler:  0
    IPC::Run:             0
    MIME::Types:          0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
